import {
  ASSIGN_DATA,
  MERGE_DATA,
  REINITIALIZE_DATA,
  SET_DATA,
  assignData,
  createDataReducer,
  deleteData,
  fetchData,
  getNormalizedDeletedState,
  getNormalizedMergedState,
  getStateKeyFromApiPath,
  getStateKeyFromUrl,
  mergeData,
  requestData,
  reinitializeData,
  selectEntitiesByKeyAndJoin,
  selectEntityByKeyAndId,
  setData,
} from 'fetch-normalize-data'

import { API_ERROR, SERVER_ERROR } from './error_codes'

export {
  API_ERROR,
  SERVER_ERROR,
  ASSIGN_DATA,
  MERGE_DATA,
  REINITIALIZE_DATA,
  SET_DATA,
  assignData,
  createDataReducer,
  deleteData,
  fetchData,
  getNormalizedDeletedState,
  getNormalizedMergedState,
  getStateKeyFromApiPath,
  getStateKeyFromUrl,
  mergeData,
  requestData,
  reinitializeData,
  selectEntitiesByKeyAndJoin,
  selectEntityByKeyAndId,
  setData,
}
export * from './watchDataActions'
