import {
  ASSIGN_DATA,
  MERGE_DATA,
  RESET_DATA,
  SET_DATA,
  assignData,
  createDataReducer,
  deleteData,
  fetchData,
  getNormalizedDeletedState,
  getNormalizedMergedState,
  mergeData,
  requestData,
  resetData,
  selectEntitiesByKeyAndJoin,
  selectEntityByKeyAndId,
  setData,
} from 'fetch-normalize-data'

export {
  ASSIGN_DATA,
  MERGE_DATA,
  RESET_DATA,
  SET_DATA,
  assignData,
  createDataReducer,
  deleteData,
  fetchData,
  getNormalizedDeletedState,
  getNormalizedMergedState,
  mergeData,
  requestData,
  resetData,
  selectEntitiesByKeyAndJoin,
  selectEntityByKeyAndId,
  setData,
}
export * from './watchDataActions'
